### ISSUE TITLE
Non-conforming effect names

### ISSUE THREAD

**Issue by mietek** [purescript/purescript-datetime#21]
The PureScript convention for effects names appears to be `SCREAMING_SNAKE_CASE`.  The `Locale` and `Now` effects should be renamed.

Perhaps it’s worth considering whether `Now` should be renamed to something different than `NOW`.  If `LOCALE` is the effect of reading the current system locale/timezone, then maybe we should go with `CLOCK`?

**Comment by jdegoes** [comment]
:+1:

**Comment by garyb** [comment]
This has been updated at last. Thanks for the report!

**Comment by garyb** [comment]
Well, the're just uppercase'd and reside in `purescript-now` instead of the core datetime library. I did consider using `CLOCK`, but after a bit of thought I decided to stick with `NOW`, as `CLOCK` could suggest time-without-date. `NOW` is not a great name either, but it's at least consistent with the corresponding functions.
