### ISSUE TITLE
How to format a DateTime object into a string

### ISSUE THREAD

**Issue by chris-kahn** [purescript/purescript-datetime#41]
How can a `DateTime` object from this library be printed to a string using a specific format? Does this need to be done manually or with another library? For example in MomentJS there is the `format` function.

**Comment by garyb** [comment]
Yeah, we don't provide any parsing or printing functions with this library by design - to keep it unopinionated about that sort of thing, but providing a base set of types that (hopefully) everyone will use.

https://github.com/slamdata/purescript-formatters is probably the kind of thing you're looking for - although it hasn't been updated for PureScript 0.10 yet.

We should probably add a note to explain the above in the README and provide links to libraries like `-formatters` that fill in the extra capabilities you'd usually find.

**Comment by chris-kahn** [comment]
Ah, makes sense, an explanation would be a good idea and maybe a link to the formatters repository. I'm guessing that also means there's no intention to provide instances for Argonaut's Encode/DecodeJson?

I'm new to Purescript and really liking it so far, but this is a bit of a pain point, it seems like I need to create a dozen DecodeJson instances and newtype wrappers and all the associated plumbing code, because of disallowed orphaned instances. Whereas in Haskell I just use `Aeson` which provides instances for all the common types. I guess this isn't the right venue to ask about the best practice w.r.t. json!

**Comment by chris-kahn** [comment]
I'll mark this closed though since that answers my question :)
