### ISSUE TITLE
Function to convert unix timestamp to DateTime?

### ISSUE THREAD

**Issue by justinwoo** [purescript/purescript-datetime#63]
It's just a combination of existing functions, I guess, but could be nice to have as a "go to solution"

**Comment by garyb** [comment]
Isn't that `toDateTime` in `Data.DateTime.Instant`?

**Comment by paulyoung** [comment]
I've been using `parse` from `purescript-js-date` and then `toDateTime`.

I opening https://github.com/purescript-contrib/purescript-js-date/issues/15 about how `parse` is somewhat unsafe.

**Comment by paulyoung** [comment]
To clarify; the `toDateTime` I referenced is from `Data.JSDate`, not this package.

**Comment by hdgarrood** [comment]
If "unix timestamp" is meant in the sense of "an int32 number of seconds since midnight, Jan 1, 1970", then this function is essentially `toDateTime` as @garyb pointed out. If "unix timestamp" is meant in the sense of the string output of the unix `date` command, e.g.
```
Fri 25 Sep 12:51:49 BST 2020
```
then this is out of scope for this library, according to the readme. Should we close this?

**Comment by JordanMartinez** [comment]
Sure.
