### ISSUE TITLE
addDays

### ISSUE THREAD

**Issue by mschristiansen** [purescript/purescript-datetime#72]
Would there be interest in a PR for an `addDays :: Int -> Date -> Date` function or same functionality under different name?

**Comment by garyb** [comment]
This is what the `adjust` function is for, but it's only defined for `DateTime` at the moment - it's workaroundable though, by turning the `Date` into a `DateTime` with a zero-time component, and then pulling the `Date` back out again after `adjust`.

**Comment by mschristiansen** [comment]
I'm writing a fair amount of Purescript code and often end up writing small functions that seems they should be in a library. Are you available on the purescript channel on freenode or somewhere else for a quick chat by any chance?

**Comment by garyb** [comment]
You can find me on the Slack channel, but I don't frequent IRC anymore I'm afraid.

You might be running into something which is kinda intentional. From an [oft-linked message in the Haskell mailing list](https://mail.haskell.org/pipermail/libraries/2012-February/017548.html):

> The Fairbairn threshold is the point at which the effort of looking up or keeping track of the definition is outweighed by the effort of rederiving it or inlining it.

`addDays n` as described in here would be `adjust (Days n)` (well, strictly speaking, `adjust (Days (Int.toNumber n))`) so given it's ~16 characters more to use the general version it doesn't really seem worth having a dedicated function for.

True enough that `adjust` should be available for `Date` alone though, if that's what you're getting at. That's something I haven't gotten around to resolving yet, as I'd like to fix it without resorting to futher expanding the FFI usage this library has (but shouldn't actually need).

**Comment by mschristiansen** [comment]
I've created PR #73 to add adjust for date, which would close this issue.

**Comment by mschristiansen** [comment]
@garyb are you around?
